image: docker

services:
  - docker:dind

stages:
  - build

variables:
  IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH/$CI_BUILD_REF_NAME

build:
  stage: build
  only:
    - develop
    - master
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE .
    - docker push $IMAGE
